app:
  name: pusher
  port: 8081
  env: local # local, dev, prod

pprof:
  enable: true
  prot: 6060

redis:  
  host: localhost
  port: 6379
  password: ""
  db: 0

source:
  redis:
    - "topic1"
  kafka:
    - "topic2"
    - "topic3"

logger:
  level: info

kafka:
  servers: "localhost"
  groupID: "consumer"
  autoOffsetReset: "latest"